# Generated by Django 5.2.6 on 2025-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='hi', max_length=40),
            preserve_default=False,
        ),
    ]
