# Generated by Django 5.2.6 on 2025-10-15 08:48

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='myapp.users'),
        ),
        migrations.AlterField(
            model_name='books',
            name='users_who_like',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='myapp.users'),
        ),
    ]
