# Generated by Django 5.2.6 on 2025-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='this is an old data', verbose_name=200),
            preserve_default=False,
        ),
    ]
