# Generated by Django 5.2.6 on 2025-10-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.courses'),
        ),
    ]
